// Objective-C API for talking to github.com/breez/breez/bindings Go package.
//   gobind -lang=objc github.com/breez/breez/bindings
//
// File is generated by gobind. Do not edit.

#ifndef __Bindings_H__
#define __Bindings_H__

@import Foundation;
#include "Universe.objc.h"


@class BindingsBreezLogger;
@protocol BindingsAppServices;
@class BindingsAppServices;
@protocol BindingsBackupService;
@class BindingsBackupService;
@protocol BindingsJobController;
@class BindingsJobController;
@protocol BindingsLogger;
@class BindingsLogger;

@protocol BindingsAppServices <NSObject>
- (NSString*)backupProviderName;
- (NSString*)backupProviderSignIn:(NSError**)error;
- (void)notify:(NSData*)notificationEvent;
@end

@protocol BindingsBackupService <NSObject>
- (BOOL)backup:(NSString*)files nodeID:(NSString*)nodeID backupID:(NSString*)backupID error:(NSError**)error;
@end

@protocol BindingsJobController <NSObject>
- (BOOL)run:(NSError**)error;
- (void)stop;
@end

@protocol BindingsLogger <NSObject>
- (void)log:(NSString*)msg lvl:(NSString*)lvl;
@end

@interface BindingsBreezLogger : NSObject <goSeqRefInterface, BindingsLogger> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (void)log:(NSString*)msg lvl:(NSString*)lvl;
@end

FOUNDATION_EXPORT NSData* BindingsAddFundsInit(NSString* breezID, NSError** error);

FOUNDATION_EXPORT NSString* BindingsAddInvoice(NSData* invoice, NSError** error);

FOUNDATION_EXPORT NSString* BindingsAvailableSnapshots(NSString* nodeID, NSError** error);

FOUNDATION_EXPORT BOOL BindingsBootstrapFiles(NSData* request, NSError** error);

FOUNDATION_EXPORT BOOL BindingsConnectAccount(NSError** error);

FOUNDATION_EXPORT NSData* BindingsCreateRatchetSession(NSData* request, NSError** error);

FOUNDATION_EXPORT BOOL BindingsDaemonReady(void);

FOUNDATION_EXPORT NSData* BindingsDecodePaymentRequest(NSString* paymentRequest, NSError** error);

FOUNDATION_EXPORT BOOL BindingsEnableAccount(BOOL enabled, NSError** error);

FOUNDATION_EXPORT NSData* BindingsGetAccountInfo(NSError** error);

FOUNDATION_EXPORT int64_t BindingsGetDefaultOnChainFeeRate(void);

FOUNDATION_EXPORT NSData* BindingsGetFundStatus(NSString* notificationToken, NSError** error);

FOUNDATION_EXPORT NSString* BindingsGetLogPath(void);

FOUNDATION_EXPORT id<BindingsLogger> BindingsGetLogger(NSString* appDir, NSError** error);

FOUNDATION_EXPORT NSData* BindingsGetPayments(NSError** error);

FOUNDATION_EXPORT NSData* BindingsGetRefundableSwapAddresses(NSError** error);

FOUNDATION_EXPORT NSData* BindingsGetRelatedInvoice(NSString* paymentRequest, NSError** error);

FOUNDATION_EXPORT BOOL BindingsInit(NSString* tempDir, NSString* workingDir, id<BindingsAppServices> services, NSError** error);

FOUNDATION_EXPORT BOOL BindingsIsConnectedToRoutingNode(void);

FOUNDATION_EXPORT void BindingsLog(NSString* msg, NSString* lvl);

FOUNDATION_EXPORT id<BindingsJobController> BindingsNewClosedChannelsJob(NSString* workingDir, NSError** error);

FOUNDATION_EXPORT id<BindingsJobController> BindingsNewSyncJob(NSString* workingDir, NSError** error);

FOUNDATION_EXPORT void BindingsOnResume(void);

FOUNDATION_EXPORT NSString* BindingsRatchetDecrypt(NSData* request, NSError** error);

FOUNDATION_EXPORT NSString* BindingsRatchetEncrypt(NSData* request, NSError** error);

FOUNDATION_EXPORT NSData* BindingsRatchetSessionInfo(NSString* sessionID, NSError** error);

FOUNDATION_EXPORT BOOL BindingsRatchetSessionSetInfo(NSData* request, NSError** error);

FOUNDATION_EXPORT NSString* BindingsRefund(NSData* refundRequest, NSError** error);

FOUNDATION_EXPORT BOOL BindingsRegisterChannelOpenedNotification(NSString* token, NSError** error);

FOUNDATION_EXPORT BOOL BindingsRegisterPeriodicSync(NSString* token, NSError** error);

FOUNDATION_EXPORT BOOL BindingsRegisterReceivePaymentReadyNotification(NSString* token, NSError** error);

FOUNDATION_EXPORT NSData* BindingsRemoveFund(NSData* removeFundRequest, NSError** error);

FOUNDATION_EXPORT void BindingsRequestBackup(void);

FOUNDATION_EXPORT BOOL BindingsRestoreBackup(NSString* nodeID, NSError** error);

FOUNDATION_EXPORT NSString* BindingsSendCommand(NSString* command, NSError** error);

FOUNDATION_EXPORT BOOL BindingsSendPaymentFailureBugReport(NSString* report, NSError** error);

FOUNDATION_EXPORT NSData* BindingsSendPaymentForRequest(NSData* payInvoiceRequest, NSError** error);

FOUNDATION_EXPORT NSString* BindingsSendWalletCoins(NSData* sendCoinsRequest, NSError** error);

FOUNDATION_EXPORT BOOL BindingsStart(NSError** error);

FOUNDATION_EXPORT void BindingsStop(void);

FOUNDATION_EXPORT BOOL BindingsValidateAddress(NSString* address, NSError** error);

FOUNDATION_EXPORT void BindingsWaitDaemonShutdown(void);

@class BindingsAppServices;

@class BindingsBackupService;

@class BindingsJobController;

@class BindingsLogger;

@interface BindingsAppServices : NSObject <goSeqRefInterface, BindingsAppServices> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (NSString*)backupProviderName;
- (NSString*)backupProviderSignIn:(NSError**)error;
- (void)notify:(NSData*)notificationEvent;
@end

@interface BindingsBackupService : NSObject <goSeqRefInterface, BindingsBackupService> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (BOOL)backup:(NSString*)files nodeID:(NSString*)nodeID backupID:(NSString*)backupID error:(NSError**)error;
@end

@interface BindingsJobController : NSObject <goSeqRefInterface, BindingsJobController> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (BOOL)run:(NSError**)error;
- (void)stop;
@end

@interface BindingsLogger : NSObject <goSeqRefInterface, BindingsLogger> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)log:(NSString*)msg lvl:(NSString*)lvl;
@end

#endif
